// Profile and work details from LinkedIn; education is a placeholder.

import { m } from "@/paraglide/messages";
import type { Locale } from "@/paraglide/runtime";

export const profile = {
  name: "Francisco Bongiovanni",
  handle: "frantssb",
  utcOffset: -3,
  email: "frantss.bongiovanni@gmail.com",
  links: [
    { platform: "github", label: "GitHub", href: "https://github.com/Frantss/" },
    { platform: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/frantssb/" },
    { platform: "x", label: "X", href: "https://x.com/frantssb" },
    { platform: "instagram", label: "Instagram", href: "https://www.instagram.com/frantss.b" },
  ],
};

// Generated by `pnpm generate:resume` from the /resume page.
export function portfolio_resume(locale: Locale) {
  return {
    href: `/resume-${locale}.pdf`,
    filename: `${profile.handle}-resume-${locale}.pdf`,
  };
}

export function portfolio_bio(locale: Locale) {
  const options = { locale };
  return {
    role: m.profile_role({}, options),
    location: m.profile_location({}, options),
    about: [
      m.profile_about_intro({}, options),
      m.profile_about_background({}, options),
      m.profile_about_personal({}, options),
    ],
  };
}

export type Job = {
  company: string;
  href?: string;
  location: string;
  role: string;
  type: string;
  start: string;
  end: string;
  bullets: string[];
  stack: string[];
};

export function portfolio_jobs(locale: Locale): Job[] {
  const options = { locale };
  return [
    {
      company: "Guildara",
      href: "https://www.guildara.com/",
      location: `Uruguay · ${m.job_remote({}, options)}`,
      role: m.job_product_engineer({}, options),
      type: m.job_full_time({}, options),
      start: "08.2023",
      end: "∞",
      bullets: [],
      stack: ["React", "Next.js", "TypeScript"],
    },
    {
      company: "Qubika",
      href: "https://qubika.com/",
      location: `Uruguay · ${m.job_remote({}, options)}`,
      role: m.job_technical_leader({}, options),
      type: m.job_full_time({}, options),
      start: "01.2022",
      end: "08.2023",
      bullets: [m.job_qubika_architecture({}, options), m.job_qubika_leadership({}, options)],
      stack: [],
    },
    {
      company: "Qubika",
      href: "https://qubika.com/",
      location: "Uruguay",
      role: m.job_fullstack({}, options),
      type: m.job_full_time({}, options),
      start: "02.2020",
      end: "08.2023",
      bullets: [m.job_qubika_development({}, options), m.job_qubika_mentoring({}, options)],
      stack: [
        "React",
        "Node.js",
        "Redux",
        "GraphQL",
        "NestJS",
        "Next.js",
        "WebSockets",
        "Terraform",
        "Cypress",
        "REST",
        "MySQL",
        "PostgreSQL",
        "AWS",
        "Datadog",
      ],
    },
    {
      company: "Datum Source",
      location: `Uruguay · ${m.job_remote({}, options)}`,
      role: m.job_react_fullstack({}, options),
      type: m.job_contract({}, options),
      start: "01.2023",
      end: "04.2023",
      bullets: [m.job_datum_mvp({}, options)],
      stack: ["Node.js", "React"],
    },
    {
      company: "Hulu",
      location: `Uruguay · ${m.job_remote({}, options)}`,
      role: m.job_fullstack({}, options),
      type: m.job_contract({}, options),
      start: "04.2020",
      end: "10.2022",
      bullets: [m.job_hulu_services({}, options), m.job_hulu_practices({}, options)],
      stack: [],
    },
    {
      company: "Senpai Academy",
      href: "https://www.senpaiacademy.com/",
      location: "Uruguay",
      role: m.job_fullstack_teacher({}, options),
      type: m.job_contract({}, options),
      start: "06.2021",
      end: "09.2021",
      bullets: [],
      stack: [],
    },
    {
      company: "ST Consultores",
      location: "Uruguay",
      role: m.job_java({}, options),
      type: m.job_part_time({}, options),
      start: "09.2019",
      end: "11.2019",
      bullets: [],
      stack: ["Java"],
    },
  ];
}

type ProjectKind = "oss" | "client" | "snippets" | "misc";

export type Project = {
  name: string;
  year?: string;
  description: string;
  href: string;
  kind: ProjectKind;
};

function portfolio_projects(locale: Locale): Project[] {
  const options = { locale };
  return [
    {
      name: "safeish",
      description: m.project_safeish_description({}, options),
      href: "https://github.com/Frantss/safeish",
      kind: "oss",
    },
    {
      name: "altereco.com.uy",
      description: m.project_altereco_description({}, options),
      href: "https://altereco.com.uy",
      kind: "client",
    },
    {
      name: "oxform",
      description: m.project_oxform_description({}, options),
      href: "https://github.com/Frantss/oxform",
      kind: "oss",
    },
    {
      name: "frantssb",
      description: m.project_frantssb_description({}, options),
      href: "https://github.com/Frantss/frantssb",
      kind: "oss",
    },
    {
      name: "ruby-memcached",
      description: m.project_ruby_memcached_description({}, options),
      href: "https://github.com/Frantss/ruby-memcached",
      kind: "misc",
    },
    {
      name: "react-hookful",
      description: m.project_react_hookful_description({}, options),
      href: "https://github.com/Frantss/react-hookful",
      kind: "misc",
    },
    {
      name: "npms-lib",
      description: m.project_npms_lib_description({}, options),
      href: "https://github.com/Frantss/npms-lib",
      kind: "misc",
    },
    {
      name: "atenea-coffee.com",
      description: m.project_atenea_description({}, options),
      href: "https://atenea-coffee.com",
      kind: "client",
    },
    {
      name: "StoreAttachment",
      description: m.project_store_attachment_description({}, options),
      href: "https://gist.github.com/Frantss/7c71fa69fd8cf754a55acf4557e2111f",
      kind: "snippets",
    },
  ];
}

export function portfolio_project_groups(locale: Locale) {
  const options = { locale };
  const projects = portfolio_projects(locale);
  return [
    { kind: "oss", label: m.project_group_oss({}, options) },
    { kind: "client", label: m.project_group_client({}, options) },
    { kind: "snippets", label: m.project_group_snippets({}, options) },
    { kind: "misc", label: m.project_group_misc({}, options) },
  ]
    .map((group) => ({ ...group, projects: projects.filter((p) => p.kind === group.kind) }))
    .filter((group) => group.projects.length > 0);
}

export function portfolio_education(locale: Locale) {
  const options = { locale };
  return [
    {
      school: m.education_school({}, options),
      degree: m.education_degree({}, options),
      years: "2015–2019",
    },
  ];
}

export const stack = [
  "TypeScript",
  "Solid",
  "React",
  "Node.js",
  "Postgres",
  "Tailwind CSS",
  "Vite",
  "Docker",
];
