// Placeholder content: replace with real resume data.

import { m } from "@/paraglide/messages";
import { baseLocale, type Locale } from "@/paraglide/runtime";

export const profile = {
  name: "Frantss Bongiovanni",
  handle: "frantssb",
  utcOffset: -3,
  email: "hello@example.com",
  links: [
    { label: "GitHub", href: "https://github.com/" },
    { label: "LinkedIn", href: "https://www.linkedin.com/" },
    { label: "X", href: "https://x.com/" },
  ],
};

// Generated by `pnpm generate-resume` from the /resume page.
export function portfolio_resume(locale: Locale) {
  return {
    href: `/resume-${locale}.pdf`,
    filename: `${profile.handle}-resume-${locale}.pdf`,
  };
}

export function portfolio_bio(locale: Locale) {
  const options = { locale };
  return {
    role: m.profile_role({}, options),
    location: m.profile_location({}, options),
    about: [m.profile_about_intro({}, options), m.profile_about_background({}, options)],
  };
}

export type Job = {
  company: string;
  location: string;
  role: string;
  type: string;
  start: string;
  end: string;
  duration: string;
  bullets: string[];
  stack: string[];
};

export function portfolio_jobs(locale: Locale): Job[] {
  const options = { locale };
  return [
    {
      company: m.job_company_one({}, options),
      location: m.job_remote({}, options),
      role: m.job_senior_engineer({}, options),
      type: m.job_full_time({}, options),
      start: "01.2024",
      end: "∞",
      duration: m.job_duration({ years: 1, months: 9 }, options),
      bullets: [m.job_one_dashboard({}, options), m.job_one_design_system({}, options)],
      stack: ["TypeScript", "Solid", "TanStack", "Postgres"],
    },
    {
      company: m.job_company_two({}, options),
      location: "São Paulo, BR",
      role: m.job_engineer({}, options),
      type: m.job_full_time({}, options),
      start: "03.2021",
      end: "12.2023",
      duration: m.job_duration({ years: 2, months: 10 }, options),
      bullets: [m.job_two_billing({}, options), m.job_two_tests({}, options)],
      stack: ["React", "Node.js", "AWS"],
    },
    {
      company: m.job_company_three({}, options),
      location: m.job_hybrid({}, options),
      role: m.job_frontend({}, options),
      type: m.job_contract({}, options),
      start: "06.2019",
      end: "02.2021",
      duration: m.job_duration({ years: 1, months: 9 }, options),
      bullets: [m.job_three_site({}, options)],
      stack: ["Vue", "Sass"],
    },
  ];
}

export type Project = { name: string; year: string; description: string; href: string };

export function portfolio_projects(locale: Locale): Project[] {
  const options = { locale };
  return [
    {
      name: "project-alpha",
      year: "2026",
      description: m.project_alpha_description({}, options),
      href: "#",
    },
    {
      name: "project-beta",
      year: "2025",
      description: m.project_beta_description({}, options),
      href: "#",
    },
    {
      name: "project-gamma",
      year: "2024",
      description: m.project_gamma_description({}, options),
      href: "#",
    },
    {
      name: "project-delta",
      year: "2023",
      description: m.project_delta_description({}, options),
      href: "#",
    },
  ];
}

export type Post = { slug: string; title: string; date: string; body: string[] };

export function portfolio_posts(locale: Locale = baseLocale): Post[] {
  const options = { locale };
  const placeholderBody = [
    m.post_body_opening({}, options),
    m.post_body_middle({}, options),
    m.post_body_closing({}, options),
  ];
  return [
    {
      slug: "notes-on-boring-architecture",
      title: m.post_boring_architecture({}, options),
      date: "2026.09.12",
      body: placeholderBody,
    },
    {
      slug: "ssr-without-the-tears",
      title: m.post_ssr({}, options),
      date: "2026.03.02",
      body: placeholderBody,
    },
    {
      slug: "what-i-learned-shipping-a-design-system",
      title: m.post_design_system({}, options),
      date: "2025.11.20",
      body: placeholderBody,
    },
    {
      slug: "on-deleting-code",
      title: m.post_deleting_code({}, options),
      date: "2025.06.08",
      body: placeholderBody,
    },
    {
      slug: "a-year-of-typescript-strict-mode",
      title: m.post_typescript({}, options),
      date: "2024.12.30",
      body: placeholderBody,
    },
  ];
}

export function portfolio_education(locale: Locale) {
  const options = { locale };
  return [
    {
      school: m.education_school({}, options),
      degree: m.education_degree({}, options),
      years: "2015–2019",
    },
  ];
}

export const stack = [
  "TypeScript",
  "Solid",
  "React",
  "Node.js",
  "Postgres",
  "Tailwind CSS",
  "Vite",
  "Docker",
];
