// Profile, work, and education details from LinkedIn.

import { m } from "@/paraglide/messages";
import type { Locale } from "@/paraglide/runtime";

export const profile = {
  name: "Francisco Bongiovanni",
  handle: "frantssb",
  utcOffset: -3,
  email: "frantss.bongiovanni@gmail.com",
  links: [
    { platform: "github", label: "GitHub", href: "https://github.com/Frantss/" },
    { platform: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/frantssb/" },
    { platform: "x", label: "X", href: "https://x.com/frantssb" },
    { platform: "instagram", label: "Instagram", href: "https://www.instagram.com/frantss.b" },
  ],
};

// Generated by `pnpm generate:cv` from the /cv page.
export function portfolio_cv(locale: Locale) {
  return {
    href: `/cv-${locale}.pdf`,
    filename: "francisco-bongiovanni-cv.pdf",
  };
}

export function portfolio_bio() {
  return {
    role: m.profile_role(),
    location: m.profile_location(),
    about: [m.profile_about_intro(), m.profile_about_background(), m.profile_about_personal()],
  };
}

export type Job = {
  company: string;
  href?: string;
  location: string;
  role: string;
  type: string;
  start: string;
  end: string;
  bullets: string[];
  stack: string[];
};

export function portfolio_jobs(): Job[] {
  return [
    {
      company: "Guildara",
      href: "https://www.guildara.com/",
      location: `Uruguay · ${m.job_remote()}`,
      role: m.job_product_engineer(),
      type: m.job_full_time(),
      start: "08.2023",
      end: "∞",
      bullets: [m.job_guildara_typescript(), m.job_guildara_codebase(), m.job_guildara_ux()],
      stack: ["React", "Next.js", "TypeScript"],
    },
    {
      company: "Qubika",
      href: "https://qubika.com/",
      location: `Uruguay · ${m.job_remote()}`,
      role: m.job_technical_leader(),
      type: m.job_full_time(),
      start: "01.2022",
      end: "08.2023",
      bullets: [m.job_qubika_architecture(), m.job_qubika_leadership()],
      stack: [],
    },
    {
      company: "Qubika",
      href: "https://qubika.com/",
      location: "Uruguay",
      role: m.job_fullstack(),
      type: m.job_full_time(),
      start: "02.2020",
      end: "08.2023",
      bullets: [m.job_qubika_development(), m.job_qubika_mentoring()],
      stack: [
        "React",
        "Node.js",
        "Redux",
        "GraphQL",
        "NestJS",
        "Next.js",
        "WebSockets",
        "Terraform",
        "Cypress",
        "REST",
        "MySQL",
        "PostgreSQL",
        "AWS",
        "Datadog",
      ],
    },
    {
      company: "Datum Source",
      location: `Uruguay · ${m.job_remote()}`,
      role: m.job_react_fullstack(),
      type: m.job_contract(),
      start: "01.2023",
      end: "04.2023",
      bullets: [m.job_datum_mvp()],
      stack: ["Node.js", "React"],
    },
    {
      company: "Hulu",
      location: `Uruguay · ${m.job_remote()}`,
      role: m.job_fullstack(),
      type: m.job_contract(),
      start: "04.2020",
      end: "10.2022",
      bullets: [m.job_hulu_services(), m.job_hulu_practices()],
      stack: [],
    },
    {
      company: "Senpai Academy",
      href: "https://www.senpaiacademy.com/",
      location: "Uruguay",
      role: m.job_fullstack_teacher(),
      type: m.job_contract(),
      start: "06.2021",
      end: "09.2021",
      bullets: [],
      stack: [],
    },
    {
      company: "ST Consultores",
      location: "Uruguay",
      role: m.job_java(),
      type: m.job_part_time(),
      start: "09.2019",
      end: "11.2019",
      bullets: [],
      stack: ["Java"],
    },
  ];
}

type ProjectKind = "oss" | "client" | "snippets" | "misc";

export type Project = {
  name: string;
  year?: string;
  description: string;
  href: string;
  kind: ProjectKind;
};

function portfolio_projects(): Project[] {
  return [
    {
      name: "safeish",
      description: m.project_safeish_description(),
      href: "https://github.com/Frantss/safeish",
      kind: "oss",
    },
    {
      name: "altereco.com.uy",
      description: m.project_altereco_description(),
      href: "https://altereco.com.uy",
      kind: "client",
    },
    {
      name: "oxform",
      description: m.project_oxform_description(),
      href: "https://github.com/Frantss/oxform",
      kind: "oss",
    },
    {
      name: "frantssb",
      description: m.project_frantssb_description(),
      href: "https://github.com/Frantss/frantssb",
      kind: "oss",
    },
    {
      name: "ruby-memcached",
      description: m.project_ruby_memcached_description(),
      href: "https://github.com/Frantss/ruby-memcached",
      kind: "misc",
    },
    {
      name: "react-hookful",
      description: m.project_react_hookful_description(),
      href: "https://github.com/Frantss/react-hookful",
      kind: "misc",
    },
    {
      name: "npms-lib",
      description: m.project_npms_lib_description(),
      href: "https://github.com/Frantss/npms-lib",
      kind: "misc",
    },
    {
      name: "atenea-coffee.com",
      description: m.project_atenea_description(),
      href: "https://atenea-coffee.com",
      kind: "client",
    },
    {
      name: "StoreAttachment",
      description: m.project_store_attachment_description(),
      href: "https://gist.github.com/Frantss/7c71fa69fd8cf754a55acf4557e2111f",
      kind: "snippets",
    },
  ];
}

export function portfolio_project_groups() {
  const projects = portfolio_projects();

  return [
    { kind: "oss", label: m.project_group_oss() },
    { kind: "client", label: m.project_group_client() },
    { kind: "snippets", label: m.project_group_snippets() },
    { kind: "misc", label: m.project_group_misc() },
  ]
    .map((group) => ({ ...group, projects: projects.filter((p) => p.kind === group.kind) }))
    .filter((group) => group.projects.length > 0);
}

export function portfolio_education() {
  return [
    {
      school: m.education_school(),
      degree: m.education_degree(),
      level: m.education_major_level(),
      years: "2022",
    },
    {
      school: "The Silesian University of Technology",
      degree: m.education_degree(),
      level: m.education_major_level(),
      years: "2019",
      description: m.education_erasmus_description(),
    },
    {
      school: m.education_school(),
      degree: m.education_analyst_degree(),
      level: m.education_intermediate_level(),
      years: "2019",
    },
    {
      school: "Alianza Cultural Uruguay-Estados Unidos",
      degree: m.education_english_certificate(),
      field: m.education_english_field(),
      years: "2018",
    },
  ];
}

export function portfolio_skills() {
  return [
    { label: m.cv_skills_languages(), items: ["TypeScript", "JavaScript", "C#", "Python"] },
    {
      label: m.cv_skills_frontend(),
      items: ["React", "Next.js", "SolidJS", "Tailwind CSS", m.cv_skills_accessibility()],
    },
    {
      label: m.cv_skills_backend(),
      items: ["GraphQL", "REST", "Node.js", "Docker", m.cv_skills_observability()],
    },
    { label: m.cv_skills_data(), items: ["PostgreSQL", "Redis"] },
    { label: m.cv_skills_cloud(), items: ["Docker", "Railway", "AWS", "Terraform"] },
  ];
}
