/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiAngryAnkylosaurusSplatRouteImport } from './routes/api.angry-ankylosaurus.$'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAngryAnkylosaurusSplatRoute =
  ApiAngryAnkylosaurusSplatRouteImport.update({
    id: '/api/angry-ankylosaurus/$',
    path: '/api/angry-ankylosaurus/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/angry-ankylosaurus/$': typeof ApiAngryAnkylosaurusSplatRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof SiteIndexRoute
  '/api/angry-ankylosaurus/$': typeof ApiAngryAnkylosaurusSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/api/angry-ankylosaurus/$': typeof ApiAngryAnkylosaurusSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/$' | '/api/angry-ankylosaurus/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/$' | '/' | '/api/angry-ankylosaurus/$'
  id: '__root__' | '/_site' | '/api/$' | '/_site/' | '/api/angry-ankylosaurus/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAngryAnkylosaurusSplatRoute: typeof ApiAngryAnkylosaurusSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/angry-ankylosaurus/$': {
      id: '/api/angry-ankylosaurus/$'
      path: '/api/angry-ankylosaurus/$'
      fullPath: '/api/angry-ankylosaurus/$'
      preLoaderRoute: typeof ApiAngryAnkylosaurusSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAngryAnkylosaurusSplatRoute: ApiAngryAnkylosaurusSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
