/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteEducationRouteImport } from './routes/_site/education'
import { Route as SiteProjectsRouteImport } from './routes/_site/projects'
import { Route as SiteWorkRouteImport } from './routes/_site/work'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as SiteWritingIndexRouteImport } from './routes/_site/writing/index'
import { Route as SiteWritingSlugRouteImport } from './routes/_site/writing/$slug'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEducationRoute = SiteEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteWorkRoute = SiteWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteWritingIndexRoute = SiteWritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteWritingSlugRoute = SiteWritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/education': typeof SiteEducationRoute
  '/projects': typeof SiteProjectsRoute
  '/work': typeof SiteWorkRoute
  '/api/$': typeof ApiSplatRoute
  '/writing/$slug': typeof SiteWritingSlugRoute
  '/writing/': typeof SiteWritingIndexRoute
}
export interface FileRoutesByTo {
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/education': typeof SiteEducationRoute
  '/projects': typeof SiteProjectsRoute
  '/work': typeof SiteWorkRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof SiteIndexRoute
  '/writing/$slug': typeof SiteWritingSlugRoute
  '/writing': typeof SiteWritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/education': typeof SiteEducationRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/work': typeof SiteWorkRoute
  '/api/$': typeof ApiSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/writing/$slug': typeof SiteWritingSlugRoute
  '/_site/writing/': typeof SiteWritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/sitemap.xml'
    | '/education'
    | '/projects'
    | '/work'
    | '/api/$'
    | '/writing/$slug'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/resume'
    | '/sitemap.xml'
    | '/education'
    | '/projects'
    | '/work'
    | '/api/$'
    | '/'
    | '/writing/$slug'
    | '/writing'
  id:
    | '__root__'
    | '/_site'
    | '/resume'
    | '/sitemap.xml'
    | '/_site/education'
    | '/_site/projects'
    | '/_site/work'
    | '/api/$'
    | '/_site/'
    | '/_site/writing/$slug'
    | '/_site/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/education': {
      id: '/_site/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof SiteEducationRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/work': {
      id: '/_site/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SiteWorkRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/writing/': {
      id: '/_site/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof SiteWritingIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/writing/$slug': {
      id: '/_site/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof SiteWritingSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteEducationRoute: typeof SiteEducationRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteWorkRoute: typeof SiteWorkRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteWritingSlugRoute: typeof SiteWritingSlugRoute
  SiteWritingIndexRoute: typeof SiteWritingIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteEducationRoute: SiteEducationRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteWorkRoute: SiteWorkRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteWritingSlugRoute: SiteWritingSlugRoute,
  SiteWritingIndexRoute: SiteWritingIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
